### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by livisky** [fex-team/fis3-plugin-relative#1]
大侠，启用的时候报错啊

在fis-config.js里添加

// 启用插件
fis.hook('relative');

// 让所有文件，都使用相对路径。
fis.match('**', {
  relative: true
});

然后 fis release -op时报错

TypeError: Object #<Object> has no method 'hook'

**Comment by oxUnd** [comment]
大侠，这是 fis3 的插件

**Comment by livisky** [comment]
大侠，看你这么认真回复，能否加个QQ？感激不尽。我的Q:262248861
