### ISSUE TITLE
[ERROR] unable to load plugin [fis3-hook-relative] or [fis-hook-relative]

### ISSUE THREAD

**Issue by nimoc** [fex-team/fis3-plugin-relative#17]
遇到个windows 的坑，将解决方法在这里记录下，方便其他同行搜索到。

按照文档，编写代码，在 win7 下出现 `[ERROR] unable to load plugin [fis3-hook-relative] or [fis-hook-relative]` 错误，mac 系统一直是没问题的。最终通过如下方法解决 win7 的问题

``` js
fis.hook(require('fis3-hook-relative'))
fis.match('**', {
    relative: true
})
```

**Comment by oxUnd** [comment]
这个应该可能是个 bug

**Comment by nimoc** [comment]
我是本地安装不是全局安装。这个 BUG 难以重现，公司有些window 是没问题的，家里 window 会出问题。也可能跟我 yarn 和 cnpm 混合安装 node 模块有关。也可能跟我混合用 GIT cmd 和 window cmd 有关。

windows 真不好测试，自动化CI测试平台都是 unix 的没看到啥 git hook触发 windows 构建的。windows 还可能跟各种环境变量配置有关
