### ISSUE TITLE
该插件貌似和csssprite冲突

### ISSUE THREAD

**Issue by w2230030100** [fex-team/fis3-plugin-relative#2]
今天用公司有人非得让我用相对路径 于是找到了这个插件 但是用的时候突然发现
spriter: fis.plugin('csssprites') 这个东西不管用了 是不是有冲突 如何解决

**Comment by rocketxujia** [comment]
是的， 我也发现这个问题：还有对应引用的图片也不压缩优化啦~

**Comment by oxUnd** [comment]
正在整理相关功能，后给兼容方法。

**Comment by w2230030100** [comment]
@xiangshouding 支持大大们 @rocketxujia 相对路径的问题可以去csssprite里的issue里解决 里面有方法 不过貌似官方没有出 有个山寨的
