### ISSUE TITLE
使用uglify-js时候出错

### ISSUE THREAD

**Issue by zidom** [fex-team/fis3-plugin-relative#4]
在使用uglify-js插件的时候，出现错误：

```
Got Error Unexpected character '\u001f'
```

经过排查是由于relative插件替换相对路径的时候留下的<code>\u001f</code>（控制台显示的是一个向下的黑三角）；
是否有进行js优化的时候，相对路径尚未处理完成？

```
optimizer: fis.plugin('uglify-js')
```

这个问题有没有解决办法？

**Comment by 2betop** [comment]
问题解决了，感谢反馈！

**Comment by 2betop** [comment]
fis3-hook-relative@1.0.4
