### ISSUE TITLE
release路径严重错误

### ISSUE THREAD

**Issue by sandmanman** [fex-team/fis3-plugin-relative#9]
release后文件路径成这样了 

``` html
<link rel="stylesheet" href=__relative("/css/application.css") />
```

fis3：v3.0.13
fis3-hook-relative： v1.0.6

**Comment by 2betop** [comment]
哪样了？

**Comment by sandmanman** [comment]
@2betop  成这样了 href=__relative("/css/application.css")   哥太迅速了

**Comment by 2betop** [comment]
你升级下这个试试 fis3-hook-relative

**Comment by sandmanman** [comment]
最新是1.0.7吧  还是这样情况  fis3 要升级到最新吗？

**Comment by 2betop** [comment]
对对， fis3 也得最新，如果要用旧版的 fis3 只能用 1.0.7 以下的 fis3-hook-relative

**Comment by sandmanman** [comment]
升级到3.3.18了  可是release -w 又报了个
Arguments to path.resolve must be strings in [/css/application.css]

我是使用@ import url("reset.css?__inline") 嵌入在application.css文件中的...

**Comment by 2betop** [comment]
这个应该是其他问题吧，你 release 的时候带上 `--verbose` 看看错误详情

**Comment by sandmanman** [comment]
可是为什么把relative注释掉，release -w正常了呢。

执行fis3 release --verbose
提示：
TypeError: Arguments to path.resolve must be strings in [/css/application.css]
    at Object.exports.resolve (path.js:116:15)
    at Object.exports.relative (path.js:239:20)
    at getRelativeUrl (D:\work\tophold-html-dev\node_modules\fis3-hook-relative\index.js:28:14)
    at D:\work\tophold-html-dev\node_modules\fis3-hook-relative\index.js:45:15
    at String.replace (native)
    at convert (D:\work\tophold-html-dev\node_modules\fis3-hook-relative\index.js:33:18)
    at EventEmitter.onProcessEnd (D:\work\tophold-html-dev\node_modules\fis3-hook-relative\index.js:91:13)
    at EventEmitter.emit (events.js:95:17)
    at Object.fis.(anonymous function) [as emit](C:UsersSandmanAppDataRoamingnpmnode_modulesfis3libfis.js:91:25)
    at process (C:\Users\Sandman\AppData\Roaming\npm\node_modules\fis3\lib\compile.js:579:7)

**Comment by 2betop** [comment]
先别内嵌了，估计是内嵌的问题，我有空看下。修复后在这回复

**Comment by sandmanman** [comment]
好的 谢谢你耐心的回复~_~

**Comment by daydayupsnail** [comment]
我也是 这个问题。同样内嵌，代码造成的大约有 40 多个html。有2个，带内嵌的 错了。 是同样的结构。
基本是从 png 图片开始错的。当一个错了之后，后面的跟着错了。不知道是不是，单个文件执行是在 文件打包之后造成的。

**Comment by woshi82** [comment]
@2betop  我也遇到相同的问题 ，我在自定义的preprocessor 插件中调用了
```javascript
            console.log('>>>>>>>>>>>>>>>>>>>>>>>>>>>>');
            console.log(content);
            console.log('<<<<<<<<<<<<<<<<<<<<<<<<<<<<');
            content = fis.compile.partial(content, temFile, {
               ext: 'html'
            });
            console.log('>>>>>>>>>>>>>>>>>>>>>>>>>>>>');
            console.log(content);
            console.log('<<<<<<<<<<<<<<<<<<<<<<<<<<<<');
```
打印结果如下：
```javascript
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<div class="home">
22
<img src="../../../assets/images/body-bg.jpg" />
<img src="../../../assets/images/body-bg.jpg" />
I am home!!
<!-- <script type="text/javascript" src="../../../libs/test.js"></script> -->
</div>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<

:::onStandardRestoreUri::::home
:::onStandardRestoreUri::::home
:::onProcessEnd::::<div class="home">
22
<img src=__relative("/assets/images/body-bg.jpg") />
<img src=__relative("/assets/images/body-bg.jpg") />
I am home!!
<!-- <script type="text/javascript" src="../../../libs/test.js"></script> -->
</div>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<div class="home">
22
<img src=__relative("/assets/images/body-bg.jpg") />
<img src=__relative("/assets/images/body-bg.jpg") />
I am home!!
<!-- <script type="text/javascript" src="../../../libs/test.js"></script> -->
</div>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

我对fis3 的APi 接口不是很了解，请问这个是监听什么的？
`fis.on('standard:restore:uri', onStandardRestoreUri);`

最后这个问题解决了么？:)

**Comment by woshi82** [comment]
@2betop  现在这个插件是没有写 file.isInline 的功能是么 ？ 香菇蓝瘦
